#ifndef CROSSLANGUAGEMATCH_INCLUDE_BUTTON_BUTTON_EVENT_H_
#define CROSSLANGUAGEMATCH_INCLUDE_BUTTON_BUTTON_EVENT_H_

namespace cross_language_match {

enum ButtonEvent {
  NONE = 0,
  PRESSED = 1
};

}

#endif //CROSSLANGUAGEMATCH_INCLUDE_BUTTON_BUTTON_EVENT_H_
